google_region = "us-central1"
google_zone = "us-central1-a"
google_instance_type = "e2-medium"
google_instance_image = "centos-cloud/centos-stream-9"
google_network = "default"
ssh_key_pub = "/home/runner/.ssh/ecdsa_ansible.pub"