name: checkers

on:
  push:
    branches:
      - iac
      
permissions: read-all

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name : Check out Git Repository
        uses: actions/checkout@v2
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0